; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = picosdk
lib_deps =
    https://github.com/misaalanshori/pico_hdmi
    
build_flags = 
   -DPICO_HDMI_RUNTIME_MODES 
   -DVIDEO_MODE_1280x720

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216