; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = picosdk
lib_deps = 
	symlink://c:\Users\misapw\Documents\gits\picoGPU\pico_hdmi
	lvgl/lvgl@^9.5.0

build_flags = 
	-Iinclude
	-DPICO_HDMI_RUNTIME_MODES
	-DVIDEO_MODE_640x480
	-DPICO_HDMI_480P_HSTX_CLK_DIV=2
	-DDISPLAY_WIDTH=640
	-DDISPLAY_HEIGHT=360
	-DPICO_STDIO_USB_BLOCKED_WRITE=0
	-DPICO_STDIO_USB_CONNECT_WAIT_TIMEOUT_MS=0
	-DPICO_STDIO_USB_STDOUT_TIMEOUT_US=0
board_upload.flash_size = 16MB	
board_upload.maximum_size = 16777216
